server:
  port: 8081

spring:
  application:
    name: googel-check
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/google_check?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000
mybatis-plus:
  #多个package用逗号或者分号分隔
  typeAliasesPackage: top.b0x0.googlecheck.totp.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则（camel case）映射
    local-cache-scope: statement   #  STATEMENT 关闭一级缓存
    call-setters-on-nulls: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1